---
apiVersion: v1
kind: Service
metadata:
  name: pharmanlp-multiarticle-summarisation-openai
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    name: pharmanlp-multiarticle-summarisation-openai
